apiVersion: pubsub.cloud.google.com/v1alpha1
kind: PullSubscription
metadata:
  name: pubsub-source-subscription-ingestion
spec:
  topic: ingestion
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: pubsub-source-subscription
  #project: krules-dev-254113
  #googleServiceAccount: cloud-run-events@krules-dev-254113.iam.gserviceaccount.com

  secret:
    name: google-cloud-key
    key: key.json
