apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: metrics-store-mongodb
  labels:
    airspot.krules.dev/type: rulesset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        airspot.krules.dev/type: rulesset
        airspot.krules.dev/rulesset: metrics-store-mongodb
    spec:
      containers:
        - name: rulesset
          env:
            - name: MONGODB_COLLECTION_RAW
              value: raw
            - name: MONGODB_COLLECTION_ERRORS
              value: errors
