apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: on-data-received-set-status
  labels:
    airspot.krules.dev/type: rulesset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        airspot.krules.dev/type: rulesset
        airspot.krules.dev/rulesset: on-data-received-set-status
    spec:
      containers:
        - name: rulesset