apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: on-data-received-store-mongodb
  labels:
    airspot.krules.dev/type: rulesset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        airspot.krules.dev/type: rulesset
        airspot.krules.dev/rulesset: on-data-received-store-mongodb
    spec:
      containers:
        - name: rulesset
          env:
            - name: MONGODB_DATABASE
              value: iot-demo-gcp-01
          volumeMounts:
            - name: mongo-db-config-volume
              mountPath: /krules/config/apps/mongodb
      volumes:
        - name: mongo-db-config-volume
          configMap:
            name: config-krules-mongodb