apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: on-data-received-set-temp-status
  labels:
    airspot.krules.dev/type: rulesset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        airspot.krules.dev/type: rulesset
    spec:
      containers:
        - name: rulesset
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: WEBSOCKET_DEVICES_NOTIFICATION_RKEY
              value: "websocket-devices-notification"
            - name: REDIS_PUBSUB_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: redis-pubsub-address
                  key: url
          volumeMounts:
            - name: config-slack-web-hooks-volume
              mountPath: /krules/config/apps/slack/web_hooks
      volumes:
        - name: config-slack-web-hooks-volume
          configMap:
            name: config-slack-web-hooks