apiVersion: sources.knative.dev/v1alpha2
kind: ContainerSource
metadata:
  name: heartbeats
spec:
  template:
    spec:
      containers:
        - image: ade8850/heartbeats-007104604b758f52b70a5535e662802b:latest
          name: heartbeats
          args:
            - --period=2
            - --eventType=krules.heartbeat
          env:
            - name: POD_NAME
              value: "heartbeats"
            - name: POD_NAMESPACE
              value: "iot-demo-gcp-01"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: scheduler
---
