apiVersion: sources.knative.dev/v1alpha2
kind: ContainerSource
metadata:
  name: heartbeats
spec:
  template:
    spec:
      containers:
        - image: eu.gcr.io/airspot/heartbeats-1c2797901d077071b664df50ca35a17f@sha256:a159f7ba18aacf588fc470fe483efac29d8046ec77742bee63587f0a6dee8582
          name: heartbeats
          args:
            - --period=2
            - --eventType=krules.heartbeat
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
  sink:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: scheduler
---
