apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: scheduler
  labels:
    airspot.krules.dev/type: rulesset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        airspot.krules.dev/type: rulesset
        airspot.krules.dev/rulesset: scheduler
        app-domain: scheduler
    spec:
      containers:
        - name: rulesset
          env:
            - name: KRULES_APPS_SCHEDULER_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-krules-scheduler-mongodb-auth
                  key: password
          volumeMounts:
            - name: config-krules-scheduler-mongodb-volume
              mountPath: /krules/config/apps/scheduler/mongodb

      volumes:
        - name: config-krules-scheduler-mongodb-volume
          configMap:
            name: config-krules-scheduler-mongodb