apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: metrics-trigger-got-errors
spec:
  broker: rules-metrics
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: metrics-got-errors
