apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: on-gcs-csv-upload
  labels:
    airspot.krules.dev/type: rulesset
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
      labels:
        airspot.krules.dev/type: rulesset
    spec:
      containers:
        - name: rulesset
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: LOGGING_LEVEL
              value: "10"
#            - name: CORE_LOGGING_LEVEL
#              value: "10"
#            - name: ROUTER_LOGGING_LEVEL
#              value: "10"
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google

      volumes:
        - name: google-cloud-key
          secret:
            secretName: google-cloud-key

