apiVersion: apps/v1
kind: Deployment
metadata:
  name: class-b-event-display
spec:
  selector:
    matchLabels:
      app: class-b-event-display
  template:
    metadata:
      labels:
        app: class-b-event-display
    spec:
      containers:
      - name: event-display
        image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: class-b-event-display
spec:
  selector:
    app: class-b-event-display
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: class-b-event-display-trigger
spec:
  broker: class-b
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: class-b-event-display
---