---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      containers:
        - name: ws-server
          image: "ade8850/websocket-server:1c28c194afa2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: ws-server
              containerPort: 5678
          env:
            - name: WEBSOCKET_DEVICES_NOTIFICATION_RKEY
              value: "websocket-devices-notification"
            - name: REDIS_PUBSUB_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: redis-pubsub-address
                  key: url
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-backend-config
spec:
  timeoutSec: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: ws-server
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"my-backend-config"}}'
  labels:
    app: ws-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
  selector:
    app: ws-server
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ws-ingress
spec:
  rules:
    - http:
        paths:
        - path: /
          backend:
            serviceName: ws-server
            servicePort: 80