apiVersion: events.cloud.google.com/v1alpha1
kind: CloudPubSubSource
metadata:
  name: pubsub-source-subscription-ingestion
spec:
  topic: ingestion
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: pubsub-source-subscription

  secret:
    name: google-cloud-key
    key: key.json
