apiVersion: v1
kind: ConfigMap
metadata:
  name: config-krules-mongodb
data:
  config_subjects_mongodb.yaml: |
    client_args:
      - mongodb.kube-public
    client_kwargs:
      authSource: admin
      username: iot-demo-gcp-01
      password: $MONGODB_PASSWORD
    database: iot-demo-gcp-01
