apiVersion: v1
kind: ConfigMap
metadata:
  name: config-slack-web-hooks
data:
  config_slack_web_hooks.yaml: |
    devices_channel_url: https://hooks.slack.com/services/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
    errors_url: https://hooks.slack.com/services/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
