# from https://medium.com/@dilipkumar/standalone-mongodb-on-kubernetes-cluster-19e7b5896b27
# TODO: complete steps
# We have no secrets and NO PERSISTENCE!!
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb-standalone
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: admin
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: password
#      nodeSelector:
#        kubernetes.io/hostname: mongodb-node
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
