apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: extapi-server
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: extapi-server
          image: "eu.gcr.io/krules-dev-254113/ext-api:0.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USER
              value: kr-demo
#              valueFrom:
#                secretKeyRef:
#                  name: extapi-secret
#                  key: username
            - name: DB_PASSWORD
              value: adM8850btz
#              valueFrom:
#                secretKeyRef:
#                  name: extapi-secret
#                  key: password
            - name: DB_NAME
              value : kr-demo
            - name: FORCE_SERVICE_UNAVAILABLE
              value: "False"
#          volumeMounts:
#            - name: extapi-secret-volume
#              mountPath: "/var/secrets/ext-api"
#      volumes:
#        - name: extapi-secret-volume
#          secret:
#            secretName: extapi-secret
